rootProject.name="Meteor"

include(":app-android")
include(":app-common")
include(":app-desktop")
include(":awt")
include(":osrs")
include(":annotations")
include(":eventbus")
include(":logger")
include(":cache")
include(":deobfuscator")
include(":api")
include(":api-rs")
include(":injector")
include(":mixins")
include(":scripts")
include(":http")
